/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BlogPost = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'content' : IDL.Text,
  'isPublished' : IDL.Bool,
  'tags' : IDL.Vec(IDL.Text),
  'publishedAt' : IDL.Int,
  'readTime' : IDL.Text,
  'excerpt' : IDL.Text,
  'category' : IDL.Text,
});
export const CreateBlogResult = IDL.Variant({
  'ok' : BlogPost,
  'err' : IDL.Text,
});
export const ContactMessage = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'timestamp' : IDL.Int,
});
export const ProfileImage = IDL.Record({
  'key' : IDL.Text,
  'url' : IDL.Text,
  'updatedAt' : IDL.Int,
});
export const SubmitResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });

export const idlService = IDL.Service({
  'createBlog' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
      [CreateBlogResult],
      [],
    ),
  'deleteBlog' : IDL.Func([IDL.Nat], [IDL.Bool], []),
  'getBlog' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
  'getBlogs' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
  'getProfileImage' : IDL.Func([], [IDL.Opt(ProfileImage)], ['query']),
  'setProfileImage' : IDL.Func([IDL.Text, IDL.Text], [ProfileImage], []),
  'submitContact' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [SubmitResult],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BlogPost = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'content' : IDL.Text,
    'isPublished' : IDL.Bool,
    'tags' : IDL.Vec(IDL.Text),
    'publishedAt' : IDL.Int,
    'readTime' : IDL.Text,
    'excerpt' : IDL.Text,
    'category' : IDL.Text,
  });
  const CreateBlogResult = IDL.Variant({ 'ok' : BlogPost, 'err' : IDL.Text });
  const ContactMessage = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  const ProfileImage = IDL.Record({
    'key' : IDL.Text,
    'url' : IDL.Text,
    'updatedAt' : IDL.Int,
  });
  const SubmitResult = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  
  return IDL.Service({
    'createBlog' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Text, IDL.Vec(IDL.Text), IDL.Text],
        [CreateBlogResult],
        [],
      ),
    'deleteBlog' : IDL.Func([IDL.Nat], [IDL.Bool], []),
    'getBlog' : IDL.Func([IDL.Nat], [IDL.Opt(BlogPost)], ['query']),
    'getBlogs' : IDL.Func([], [IDL.Vec(BlogPost)], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(ContactMessage)], ['query']),
    'getProfileImage' : IDL.Func([], [IDL.Opt(ProfileImage)], ['query']),
    'setProfileImage' : IDL.Func([IDL.Text, IDL.Text], [ProfileImage], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [SubmitResult],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };