/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BlogPost {
  'id' : bigint,
  'title' : string,
  'content' : string,
  'isPublished' : boolean,
  'tags' : Array<string>,
  'publishedAt' : bigint,
  'readTime' : string,
  'excerpt' : string,
  'category' : string,
}
export interface ContactMessage {
  'id' : bigint,
  'name' : string,
  'email' : string,
  'message' : string,
  'timestamp' : bigint,
}
export type CreateBlogResult = { 'ok' : BlogPost } |
  { 'err' : string };
export interface ProfileImage {
  'key' : string,
  'url' : string,
  'updatedAt' : bigint,
}
export type SubmitResult = { 'ok' : bigint } |
  { 'err' : string };
export interface _SERVICE {
  'createBlog' : ActorMethod<
    [string, string, string, string, Array<string>, string],
    CreateBlogResult
  >,
  'deleteBlog' : ActorMethod<[bigint], boolean>,
  'getBlog' : ActorMethod<[bigint], [] | [BlogPost]>,
  'getBlogs' : ActorMethod<[], Array<BlogPost>>,
  'getContacts' : ActorMethod<[], Array<ContactMessage>>,
  'getProfileImage' : ActorMethod<[], [] | [ProfileImage]>,
  'setProfileImage' : ActorMethod<[string, string], ProfileImage>,
  'submitContact' : ActorMethod<[string, string, string], SubmitResult>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];